apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  type: ExternalName
  externalName: 172.22.0.7
  ports:
    - port: 5001
      targetPort: 5000
      protocol: TCP
      name: http