replicaCount: 1
image:
  repository: regorp-registry:5000/regorp/api-gateway
  tag: "latest"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 9080
env:
  NODE_ENV: development
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
